[package]
name = "debugger"
version = "0.1.0"
license = "Unlicense"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
argh = { workspace = true }
nix = { workspace = true, features = ["process", "ptrace"] }
thiserror = { workspace = true }
