[package]
name = "debugger"
version = "0.1.0"
license = "Unlicense"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
libc = { workspace = true }
rustyline = { version = "17.0.1", features = ["with-file-history"], default-features = false }
thiserror = { workspace = true }
